package CrawlerHost;
import Crawler.*;
import SQLUtilities.*;
import java.awt.*;
import javax.swing.*;


public class CrawlerWindow extends javax.swing.JFrame {

    DataBaseDetails dbDetails = new DataBaseDetails();
    CrawlerDatabase cD = new CrawlerDatabase();
    public CrawlerWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDynamicMessage = new javax.swing.JLabel();
        labelHeader = new javax.swing.JLabel();
        panelDataBaseDetails = new javax.swing.JPanel();
        txtFieldURL = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtFieldUserName = new javax.swing.JTextField();
        btnDone = new javax.swing.JButton();
        pswdFieldPassword = new javax.swing.JPasswordField();
        btnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFieldStartURL = new javax.swing.JTextField();
        panelStatus = new javax.swing.JPanel();
        labelLinksFound = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelCrawlerInPage = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelContentDownloaded = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelHeader.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelHeader.setText("Starting Crawler");

        txtFieldURL.setText("jdbc:mysql://localhost/crawler");

        jLabel1.setText("URL:");

        txtFieldUserName.setText("root");
        txtFieldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldUserNameActionPerformed(evt);
            }
        });

        btnDone.setText("Start Crawler");
        btnDone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDoneMouseReleased(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCancelMouseReleased(evt);
            }
        });

        jLabel2.setText("Username: ");

        jLabel4.setText("Provide DataBase Details");

        jLabel3.setText("Password:");

        jLabel8.setText("Necessary tables/databases will be created if not available.");

        jLabel9.setText("Starting URL:");

        txtFieldStartURL.setText("http://localhost/");

        javax.swing.GroupLayout panelDataBaseDetailsLayout = new javax.swing.GroupLayout(panelDataBaseDetails);
        panelDataBaseDetails.setLayout(panelDataBaseDetailsLayout);
        panelDataBaseDetailsLayout.setHorizontalGroup(
            panelDataBaseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataBaseDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDataBaseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(panelDataBaseDetailsLayout.createSequentialGroup()
                        .addGroup(panelDataBaseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDataBaseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(panelDataBaseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtFieldStartURL, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDataBaseDetailsLayout.createSequentialGroup()
                                    .addComponent(btnDone)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCancel))
                                .addComponent(txtFieldURL, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFieldUserName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pswdFieldPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        panelDataBaseDetailsLayout.setVerticalGroup(
            panelDataBaseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataBaseDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(panelDataBaseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFieldURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDataBaseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(panelDataBaseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pswdFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDataBaseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldStartURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDataBaseDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDone)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelLinksFound.setText("0");

        jLabel6.setText("Total Content Downloaded (KB)  ::");

        labelCrawlerInPage.setText("Starting............");

        jLabel5.setText("Crawler in Page ::");

        jLabel7.setText("Total Links Found ::");

        labelContentDownloaded.setText("0");

        javax.swing.GroupLayout panelStatusLayout = new javax.swing.GroupLayout(panelStatus);
        panelStatus.setLayout(panelStatusLayout);
        panelStatusLayout.setHorizontalGroup(
            panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCrawlerInPage, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLinksFound)
                    .addComponent(labelContentDownloaded, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelStatusLayout.setVerticalGroup(
            panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelCrawlerInPage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labelContentDownloaded))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(labelLinksFound))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(labelDynamicMessage))
                    .addComponent(labelHeader)
                    .addComponent(panelDataBaseDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDataBaseDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(51, 51, 51)
                .addComponent(labelDynamicMessage)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoneMouseReleased
        
        disablePanel(panelDataBaseDetails);
        changeLabelDynamicMessage("Please wait...");
        
        SQLUtilities sU = new SQLUtilities();
        String URL = txtFieldURL.getText();
        String user = txtFieldUserName.getText();
        String password = pswdFieldPassword.getText();
        
        
        dbDetails.setDataBasePassword(pswdFieldPassword.getText());
        dbDetails.setDataBaseURL(txtFieldURL.getText());
        dbDetails.setDataBaseUser(txtFieldUserName.getText());
        dbDetails.setStartURL(txtFieldStartURL.getText());
        
        if(sU.testValidSQL(URL, user, password)){
   
        labelDynamicMessage.setText("");
        dbDetails.setReady('y');
        panelDataBaseDetails.setVisible(false);
        panelStatus.setVisible(true);
        initializationCrawler();
        
        }else{
        changeLabelDynamicMessage("SQL Details INVALID. Please try again...");
        
        enablePanel(panelDataBaseDetails);
        dbDetails.setReady('n');
        }
 
    }//GEN-LAST:event_btnDoneMouseReleased

    private void initializationCrawler(){
        changeLabelHeader("Crawler now Crawling...");
        panelDataBaseDetails.setVisible(false);  
        CrawlStarter cS = new CrawlStarter();
        String contentDownloadedAndLinksFound;  
        String nextWebPageToCrawl;
        
        //TEST >>> First the table is empty so the Database has to be filled first...//
        
        nextWebPageToCrawl = cD.nextWebPageToCrawl(dbDetails);
        contentDownloadedAndLinksFound=cS.startCrawling(nextWebPageToCrawl,dbDetails);
        
        //TEST//
        
        while(!cD.nextWebPageToCrawl(dbDetails).equals("NOT FOUND") ){
        
        nextWebPageToCrawl = cD.nextWebPageToCrawl(dbDetails);
        changeCrawlerInPage(nextWebPageToCrawl);
        
        ////////////////Crawler Started HERE ///////////////////////////  
       
        contentDownloadedAndLinksFound=cS.startCrawling(nextWebPageToCrawl,dbDetails);
        
        ////////////////Crawler Started HERE ///////////////////////////

        changeContentDownloadedAndLinksFound(contentDownloadedAndLinksFound);      
        }
        changeLabelHeader("Final Statistics");

    }
    
    private void changeLabelDynamicMessage(String message){
        labelDynamicMessage.setText(message);
    }
    
    
    void changeContentDownloadedAndLinksFound(String cDALF){

        //System.out.print(cDALF);
        
        double contentDownloaded=0;
        contentDownloaded+=(Double.parseDouble(labelContentDownloaded.getText()));
        contentDownloaded*=1000;
        
        
        String recentContentDownloadedString=cDALF.substring(0, cDALF.indexOf('$'));
        Double recentContentDownloadedDouble=Double.parseDouble(recentContentDownloadedString);
        
        contentDownloaded+=recentContentDownloadedDouble;
        contentDownloaded/=1000;
        
        
        int linksFound=0;
        linksFound+=Integer.parseInt(labelLinksFound.getText());
        
        
        String recentLinksFoundString=cDALF.substring(cDALF.indexOf('$')+1);
        
        
        
        int recentLinksFoundInteger=Integer.parseInt(recentLinksFoundString);
        linksFound+=recentLinksFoundInteger;
        
        //System.out.println(contentDownloaded);
        
        
        labelContentDownloaded.setText(Double.toString(contentDownloaded)); 
   
        labelLinksFound.setText(Integer.toString(linksFound)); 
        
    }
    
    
    void changeLabelHeader(String header ){
        labelHeader.setText(header);
    }
    
    
    private void btnCancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseReleased
        System.exit(0);
    }//GEN-LAST:event_btnCancelMouseReleased

    private void txtFieldUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldUserNameActionPerformed

    private void enablePanel( javax.swing.JPanel panel  ){
        Component[] com = panel.getComponents();
        for(int a=0 ; a < com.length; a++){
            com[a].setEnabled(true);
        }
    }
    
    
    private void changeCrawlerInPage(String page){
        labelCrawlerInPage.setText(page);
    }
    
    private void disablePanel( javax.swing.JPanel panel  ){
        
        /*
        btnDone.setEnabled(false);
        btnCancel.setEnabled(false);
        pswdFieldPassword.setEnabled(false);
        txtFieldURL.setEnabled(false);
        txtFieldUserName.setEnabled(false);
        */
        
        Component[] com = panel.getComponents();
        for(int a=0 ; a < com.length; a++){
            com[a].setEnabled(false);
            
        }
        
        
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrawlerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrawlerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrawlerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrawlerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrawlerWindow().setVisible(true);
            }
        });
    }
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelContentDownloaded;
    private javax.swing.JLabel labelCrawlerInPage;
    private javax.swing.JLabel labelDynamicMessage;
    private javax.swing.JLabel labelHeader;
    private javax.swing.JLabel labelLinksFound;
    private javax.swing.JPanel panelDataBaseDetails;
    private javax.swing.JPanel panelStatus;
    private javax.swing.JPasswordField pswdFieldPassword;
    private javax.swing.JTextField txtFieldStartURL;
    private javax.swing.JTextField txtFieldURL;
    private javax.swing.JTextField txtFieldUserName;
    // End of variables declaration//GEN-END:variables
}
